# Most of the parameters will be imported from the training config
src:
  ckpt: 'bestModel/best_att.pth'
  config: 'config/chinaPopSong/asr_hybrid.yaml'
data:
  corpus:
    name:  'chinaPopSong'
    dev_split: ['dev']
    test_split: ['test']
decode:
  beam_size: 20
  min_len_ratio: 0.01
  max_len_ratio: 0.07
  lm_path: 'bestModel/best_ppx.pth'
  lm_config: 'config/chinaPopSong/lm_chinaPopSong.yaml'
  lm_weight: 0.5
  ctc_weight: 0.0